# Generated by Django 4.0.5 on 2022-07-16 07:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.FileField(default='default.jpg', upload_to='static/images/products')),
                ('productBrand', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('total', models.CharField(default='', max_length=10000)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
                'db_table': 'Order',
            },
        ),
    ]
