# Generated by Django 4.0.5 on 2022-07-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productPrice', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('techSpec', models.CharField(max_length=255)),
                ('whatsIncluded', models.CharField(max_length=255)),
                ('mainImg', models.FileField(default='default.jpg', upload_to='static/images/products')),
                ('img1', models.FileField(default='default.jpg', upload_to='static/images/products')),
                ('img2', models.FileField(default='default.jpg', upload_to='static/images/products')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
