# Generated by Django 4.0.5 on 2022-07-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
