# Generated by Django 4.0.5 on 2022-07-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productBrand',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
