# Generated by Django 4.0.5 on 2022-07-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_productbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productCategory',
            field=models.CharField(default=122, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='productBrand',
            field=models.CharField(max_length=255),
        ),
    ]
