# Generated by Django 4.0.5 on 2022-07-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_alter_products_productcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Product',
        ),
    ]
