# Generated by Django 4.0.5 on 2022-07-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_productcategory_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
