# Generated by Django 4.0.5 on 2022-07-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mainImg',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productPrice',
            new_name='price',
        ),
    ]
